language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx+30ndvTH0hgPPaf69ze5l4tKO+3cFASPiqnXZxTzTFxEhhgy3lw1hd0f1M5ZtCcnUQklIsIGam4p9X98QusYyPcmw/1SzVjSbLWHLUIWygQvGr2zIAzRzAEQG44xn8CHqGWki+aRK6XLqOqNaQt6MY4b9DhnFleuHUo+n9pL5PZ9fz323MIZJ1uD6VO1OO9Nc8qb4z3IYxsDhzTnj2h8KCnw64FcmosxbeSTbBjUMzGvnNbZdTgU3r2o9OzMG72SBCzmlD0pIR3e9LLzBTY/SiT1jld1vsFm2LceNSz6TZZeVViOPQ5bqbiKtbYn0bqL3Ja8UCsZXumejL7QEJo6fzCVBgrIuH7+SKC4R3/bVsspbqwRVHX+Y2oTGzwBId33FiAwXfWfLIUVxycpHOormdkRGyExho+4zXs0US+CUoIZyfikTDpx1FIbwR/PCFytxtPxAhnEhUzakhCFpNK1umgJ0cQpgyvzuPDRgac+AKbxhpt4=
  app: sape-fusion
